import { ChangeDetectionStrategy, Component, computed, effect, HostListener, inject, signal, Type, untracked } from '@angular/core';
import { CommonModule, NgComponentOutlet } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';import { map } from 'rxjs/operators';
import { AUDIENCE_PAGES, LevelResource } from '../core/data/page-content';import { RevealDirective } from '../shared/scroll-reveal/scroll-reveal.directive';import { AudienceSlug } from '../core/models/content.models';import { ImageLoaderDirective } from '../shared/image-loader/image-loader.directive';import { AUDIENCE_CONFIG } from './audiencia-config';import { WIDGET_REGISTRY, WidgetId } from './widget-registry';import { ResourceCardComponent } from '../shared/resource-card/resource-card';import { PROFILE_LEARNING, PROFILE_QUERY } from './profile-activities.data';
@Component({selector:'app-audiencia',standalone:true,imports:[CommonModule,NgComponentOutlet,RouterLink,RevealDirective,ImageLoaderDirective,ResourceCardComponent],changeDetection:ChangeDetectionStrategy.OnPush,templateUrl:'./audiencia.html',styleUrl:'./audiencia.css'})
export class AudienciaComponent{
 private route=inject(ActivatedRoute);private router=inject(Router);slug=toSignal(this.route.paramMap.pipe(map(p=>p.get('slug')??'')),{initialValue:''});fragment=toSignal(this.route.fragment);page=computed(()=>AUDIENCE_PAGES.find(a=>a.slug===this.slug()));config=computed(()=>AUDIENCE_CONFIG[this.slug()]??null);audienceTheme=computed<AudienceSlug>(()=>this.config()?.theme??'cdj');profileLearning=computed(()=>PROFILE_LEARNING[this.audienceTheme()]??null);profileQuery=computed(()=>PROFILE_QUERY[this.audienceTheme()]??'teens');selectedLevel=signal<string>('');activeWidgetId=signal<WidgetId|null>(null);
 showCasi=computed(()=>['kids','families','teachers'].includes(this.audienceTheme()));casiProfile=computed(()=>this.audienceTheme()==='families'?'families':this.audienceTheme()==='teachers'?'teachers':this.selectedLevel()==='primaria-alta'?'pa':'pb');
 casiCopy=computed(()=>{if(this.audienceTheme()==='families')return{k:'Historias para acompañar',t:'El día que casi… en familia',d:'Una historia compartida para escuchar qué piensan, reconocer riesgos juntos y construir acuerdos sin convertir la conversación en regaño.'};if(this.audienceTheme()==='teachers')return{k:'Detonadores para el aula',t:'El día que casi… para trabajar con el grupo',d:'Episodios breves para plantear dilemas, escuchar distintas decisiones y cerrar con acciones de ciudadanía digital aplicables al grupo.'};if(this.selectedLevel()==='primaria-alta')return{k:'Primaria alta · Serie animada',t:'El día que casi…',d:'Historias para identificar el momento en que todavía puedes detenerte, analizar una señal y tomar una decisión con mayor autonomía.'};return{k:'Primaria baja · En compañía',t:'El día que casi…',d:'Historias sencillas para reconocer cuando algo en internet no se siente bien, saber qué hacer y cuándo pedir ayuda a una persona adulta de confianza.'}});
 constructor(){effect(()=>{const cfg=this.config(),frag=this.fragment();untracked(()=>{const p=this.page();const valid=frag&&p&&p.subLevels.some(s=>s.id===frag);this.selectedLevel.set(valid?frag:(cfg?.defaultLevel??''));if(valid)setTimeout(()=>this.scrollToAnchor('actividades-nivel'),120)})});effect(()=>{this.selectedLevel();untracked(()=>this.closeWidgetModal())})}
 activeSubLevel=computed(()=>this.page()?.subLevels.find(s=>s.id===this.selectedLevel())??null);getActiveLevelName=computed(()=>this.activeSubLevel()?.title??'');levelResources=computed(()=>{let r=this.activeSubLevel()?.levelResources??[];if(this.selectedLevel()==='secundaria')r=r.filter(x=>x.typeLabel?.toLowerCase()!=='cuestionario'&&x.id!=='app-no-se-acaba');return r});activeWidget=computed<Type<unknown>|null>(()=>{const id=this.activeWidgetId();return id?(WIDGET_REGISTRY[id]??null):null});isPhoneWidget=computed(()=>{const id=this.activeWidgetId();return!!id&&['fraud-simulator','peer-pressure','sticker-control','el-carino-no-pide-contrasenas','chat-en-llamas','la-voz-en-el-squad','no-lo-hagas-viral','perfil-fantasma','monedas-gratis','jugada-problema','el-servidor-de-discor','el-mercado-gamer','el-mundo-privado','quien-entra-mi-mundo','bit-data-mensaje-gris','luna-cajita-importante'].includes(id)});
 scrollToAnchor(id:string){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}selectLevelAndScroll(id:string){if(this.selectedLevel()===id)this.scrollToAnchor('actividades-nivel');else this.router.navigate([],{fragment:id,relativeTo:this.route,replaceUrl:true})}onResourceActionClicked(item:LevelResource){const m:Record<string,WidgetId>={'simulador-fraudes':'fraud-simulator','candado-rapido':'candado-rapido','presion-pares':'peer-pressure','limites-chats':'limites-chats','presencia-adulta':'adult-presence','riesgos-reales':'riesgos-reales','presencia-jovenes':'presencia-jovenes','privacidad-dinero':'privacidad-dinero','sticker-control':'sticker-control','app-no-se-acaba':'app-no-se-acaba','el-carino-no-pide-contrasenas':'el-carino-no-pide-contrasenas','chat-en-llamas':'chat-en-llamas','la-voz-en-el-squad':'la-voz-en-el-squad','no-lo-hagas-viral':'no-lo-hagas-viral','perfil-fantasma':'perfil-fantasma','monedas-gratis':'monedas-gratis','jugada-problema':'jugada-problema','reconozco-emociones':'reconozco-emociones','bit-data-mensaje-gris':'bit-data-mensaje-gris','luna-cajita-importante':'luna-cajita-importante','el-servidor-de-discor':'el-servidor-de-discor','el-mercado-gamer':'el-mercado-gamer','el-mundo-privado':'el-mundo-privado','cuando-hijo-mundo-privado':'cuando-hijo-mundo-privado','quien-entra-mi-mundo':'quien-entra-mi-mundo'};const w=m[item.id];if(w){this.activeWidgetId.set(w);document.body.classList.add('no-scroll')}}closeWidgetModal(){this.activeWidgetId.set(null);document.body.classList.remove('no-scroll')}@HostListener('document:keydown.escape')onEscKey(){if(this.activeWidgetId())this.closeWidgetModal()}
}
