import { AudienceSlug } from '../core/models/content.models';
export interface GuidanceItem { title:string; summary:string; watch?:string; action?:string; }
export interface GuidanceBlock { eyebrow:string; title:string; intro:string; items:GuidanceItem[]; }

const KIDS_PRE:GuidanceBlock={eyebrow:'Antes de empezar',title:'Para acompañar esta etapa',intro:'En preescolar la experiencia digital se aprende principalmente con compañía, conversación y ejemplo adulto.',items:[{title:'Lo que siente también importa',summary:'Una pantalla, un video o un mensaje puede provocar alegría, miedo, enojo o confusión.',watch:'Si algo le incomoda, no minimices lo que siente.',action:'Ayúdale a nombrar la emoción y practicar: cierro, me alejo y cuento.'},{title:'Hay cosas que se cuidan',summary:'Nombre completo, fotos, voz, ubicación y datos familiares no deben compartirse sin acompañamiento.',watch:'A esta edad no corresponde que decida solo qué información entregar.',action:'Usen ejemplos sencillos de cosas que sí puede contar y cosas que primero debe consultar.'},{title:'Pedir ayuda es parte de aprender',summary:'La meta no es que resuelva solo una situación digital, sino que reconozca cuándo necesita a una persona adulta.',action:'Repitan una regla fácil: si algo me asusta, me pide un secreto o no lo entiendo, lo cuento.'},{title:'Pantalla, juego y descanso',summary:'La tecnología es una actividad más dentro del día; no necesita ocupar todos los momentos.',action:'Alternen pantalla con juego físico, conversación, sueño y actividades sin dispositivo.'}]};
const KIDS_LOW:GuidanceBlock={eyebrow:'Lo importante para ti',title:'Antes de jugar o compartir en línea',intro:'Ideas sencillas para empezar a tomar decisiones y saber cuándo pedir ayuda.',items:[{title:'Mis datos son importantes',summary:'Tu nombre completo, dirección, escuela, contraseñas, fotos y ubicación pueden decir mucho sobre ti.',action:'Antes de compartir un dato, pregunta a una persona adulta de confianza.'},{title:'No todas las personas en línea son conocidas',summary:'Un avatar o un nombre de usuario no demuestra quién está detrás de una cuenta.',watch:'Desconfía si alguien pide secretos, datos, fotos o quiere llevar la conversación a otro lugar.',action:'No respondas, sal de la conversación y cuéntalo.'},{title:'Jugar en línea también necesita acuerdos',summary:'Chats, amistades y compras dentro de los juegos son decisiones reales.',action:'Las compras y cambios de privacidad se revisan con una persona adulta.'},{title:'Ser amable también cuenta en internet',summary:'Lo que escribimos, enviamos o compartimos puede hacer sentir bien o mal a otras personas.',action:'Si algo lastima, no lo reenvíes y busca ayuda.'}]};
const KIDS_HIGH:GuidanceBlock={eyebrow:'Lo importante para ti',title:'Más autonomía, mejores decisiones',intro:'A medida que haces más cosas en línea, también puedes aprender a detenerte, revisar y decidir.',items:[{title:'Privacidad y cuentas',summary:'Configurar quién puede verte, escribirte o conocer tus datos reduce exposiciones innecesarias.',action:'Revisa privacidad y usa contraseñas diferentes; pide apoyo cuando una configuración no sea clara.'},{title:'Videojuegos, chats y compras',summary:'Las monedas virtuales, premios y ofertas pueden involucrar dinero real o intentos de engaño.',watch:'Urgencia, premios demasiado buenos y solicitudes de contraseña son señales de alerta.',action:'Pausa antes de comprar, abrir enlaces o aceptar contactos.'},{title:'Lo popular no siempre es confiable',summary:'Influencers, retos y publicaciones pueden mezclar entretenimiento, publicidad, presión y datos falsos.',action:'Pregúntate quién lo publica, para qué y qué evidencia ofrece.'},{title:'Convivencia y presión de grupo',summary:'Participar en una broma, reenviar una imagen o sumarse a un reto también tiene consecuencias.',action:'Antes de compartir, piensa si es seguro, respetuoso y si la otra persona estaría de acuerdo.'}]};

const TEENS:GuidanceBlock={eyebrow:'Lo importante para tu vida digital',title:'Palabras que vas a escuchar y conviene entender',intro:'Conocer estos términos no es para asustarte. Sirve para reconocer una situación, detenerte a tiempo y saber qué hacer.',items:[
 {title:'Phishing: cuando intentan engañarte para robar tus datos',summary:'Es un mensaje, correo o página que se hace pasar por alguien confiable para que entregues una contraseña, código, dato bancario o abras un enlace. Ejemplo: “Tu cuenta será bloqueada hoy. Entra aquí y confirma tu contraseña”.',watch:'Mensajes con mucha urgencia, premios inesperados, direcciones extrañas o solicitudes de códigos y contraseñas.',action:'No abras el enlace. Entra tú mismo a la app o sitio oficial y verifica. Nunca compartas códigos de acceso.'},
 {title:'Sexting: compartir contenido íntimo por medios digitales',summary:'Es enviar o intercambiar mensajes, fotos o videos íntimos. Puede existir entre personas que están de acuerdo, pero una imagen puede guardarse, copiarse o difundirse fuera del contexto original. Ejemplo: alguien con quien sales te pide una foto íntima y te dice que “si confías, se la mandas”.',watch:'Presión, chantaje, insistencia o cualquier difusión sin permiso.',action:'No tienes que enviar nada para demostrar confianza. Si una imagen tuya se comparte sin permiso, no la reenvíes para “comprobarlo”; guarda la información necesaria, pide apoyo a una persona de confianza y reporta la difusión.'},
 {title:'Grooming: cuando un adulto busca ganarse la confianza de un menor con fines sexuales',summary:'Puede empezar como una conversación amistosa: comparte gustos, ofrece regalos o hace sentir especial a la persona. Después puede pedir secretos, fotos íntimas, videollamadas o encuentros.',watch:'Pedir que ocultes la conversación, mover el chat a un espacio privado, regalos, preguntas sexuales o amenazas para que no cuentes nada.',action:'Corta el contacto, no envíes más contenido, conserva evidencia si es seguro hacerlo, bloquea y cuéntaselo a una persona adulta de confianza.'},
 {title:'Ciberacoso: cuando el daño también ocurre por pantallas',summary:'Son agresiones, humillaciones, amenazas o exclusión mediante chats, redes, videojuegos u otros espacios digitales. Ejemplo: crear un grupo para burlarse de alguien o compartir una foto para ridiculizarlo.',watch:'Cuando la conducta se repite, se amplifica al compartirla o hace que alguien tenga miedo de conectarse o asistir a la escuela.',action:'No respondas con otra agresión ni ayudes a difundirla. Guarda evidencia, bloquea o reporta y busca apoyo.'},
 {title:'Huella digital: lo que va quedando de tu actividad en línea',summary:'Publicaciones, comentarios, perfiles, fotos y registros pueden permanecer o circular aunque después los borres. No significa que debas tener miedo de publicar, sino pensar en contexto y audiencia.',action:'Antes de publicar pregúntate: ¿estoy de acuerdo con que esto salga de este chat o llegue a otra persona?'},
 {title:'Deepfake y contenido generado con IA',summary:'La IA puede crear o modificar imágenes, voces y videos para que parezca que una persona dijo o hizo algo que nunca ocurrió. Un video muy realista ya no es prueba suficiente por sí solo.',watch:'Contenido sorprendente sin fuente clara, cuentas que lo publican sin contexto o imágenes y audios usados para presionar o engañar.',action:'Busca la fuente original, contrasta con otras fuentes y no compartas solo porque parece real.'}
]};

const FAMILIES:GuidanceBlock={eyebrow:'Para acompañar con claridad',title:'Términos que conviene conocer en casa',intro:'No necesitas dominar la tecnología. Entender qué significa cada situación ayuda a escuchar mejor, detectar señales y responder sin convertir la primera reacción en castigo.',items:[
 {title:'Phishing y robo de cuentas',summary:'El phishing busca que una persona entregue datos o credenciales mediante un mensaje falso. Ejemplo: a su hijo le llega “ganaste monedas gratis para tu juego, inicia sesión aquí”. A un adulto puede llegarle “su paquete está retenido, pague aquí”.',watch:'Urgencia, premios, enlaces inesperados, solicitudes de contraseña o códigos de verificación.',action:'No usen el enlace recibido. Abran directamente la aplicación o sitio oficial. Si ya entregaron una contraseña, cámbienla y revisen la seguridad de la cuenta.'},
 {title:'Sexting, presión y difusión sin consentimiento',summary:'Sexting es el intercambio de contenido íntimo por medios digitales. En adolescentes puede aparecer dentro de relaciones afectivas. El problema cambia radicalmente cuando existe presión, amenaza o alguien comparte el contenido sin permiso.',watch:'Frases como “si me quisieras me mandarías una foto”, miedo a revisar el teléfono, chantaje o preocupación porque una imagen pueda circular.',action:'Si su hija o hijo pide ayuda, escuche primero y evite culpabilizarlo. No reenvíe la imagen. Ayude a conservar la información necesaria, reportar y buscar apoyo adecuado.'},
 {title:'Grooming: acercamiento de un adulto a un menor con fines sexuales',summary:'Un adulto puede construir confianza durante días o meses, fingir otra edad, compartir intereses y después pedir secretos, imágenes o encuentros.',watch:'Regalos inexplicables, conversaciones secretas, insistencia en cambiar de plataforma, solicitudes sexuales o amenazas.',action:'No confronte impulsivamente desde la cuenta del menor. Proteja al niño o adolescente, conserve evidencia cuando corresponda, bloquee o reporte y busque apoyo de las autoridades competentes si existe riesgo.'},
 {title:'Ciberacoso',summary:'No es simplemente “una pelea por WhatsApp”. Puede incluir humillación, amenazas, exclusión, cuentas falsas o difusión de contenido para lastimar.',watch:'Cambios repentinos al usar el teléfono, miedo de ir a la escuela, abandono de grupos o angustia después de conectarse.',action:'Escuche qué ocurrió antes de quitar el dispositivo. Evite aumentar la exposición, conserve evidencia y coordine la respuesta con la escuela cuando el caso involucre a la comunidad escolar.'},
 {title:'Deepfakes, IA y contenido manipulado',summary:'Hoy es posible fabricar una voz, fotografía o video convincente. También pueden crearse imágenes íntimas falsas de una persona real.',watch:'Mensajes que usan una supuesta voz o imagen para pedir dinero, amenazar o avergonzar.',action:'Verifique por otro canal antes de actuar. No difunda el material y acompañe a la persona afectada para reportarlo y buscar ayuda.'},
 {title:'Acompañar no es vigilar todo',summary:'La protección cambia con la edad. Los controles técnicos pueden ayudar, pero una relación donde pueden pedir ayuda sigue siendo fundamental.',action:'Acuerden qué se revisa, qué es privado, cuándo interviene un adulto y qué situaciones siempre deben contarse.'}
]};

const TEACHERS:GuidanceBlock={eyebrow:'Para hablarlo en el aula',title:'Conceptos digitales explicados sin tecnicismos',intro:'El objetivo no es que el alumnado memorice palabras, sino que pueda reconocer una situación, explicar por qué importa y saber cómo responder.',items:[
 {title:'Phishing',summary:'Intento de engaño para obtener contraseñas, códigos, dinero o datos mediante mensajes y sitios que imitan servicios reales. Ejemplo para clase: “Te llegó un correo que dice que perderás tu cuenta escolar si no inicias sesión en cinco minutos”.',action:'Pida al grupo identificar tres señales antes de hablar de la definición: urgencia, remitente y destino del enlace. Después practiquen verificar entrando por el canal oficial.'},
 {title:'Sexting y consentimiento',summary:'Sexting es compartir contenido íntimo mediante medios digitales. Para trabajarlo educativamente hay que distinguir entre el concepto, la presión para producir contenido y la difusión sin consentimiento. Evite convertir la sesión en un juicio sobre quien envió una imagen.',watch:'No solicite ejemplos personales ni pida al alumnado contar experiencias íntimas frente al grupo.',action:'Trabaje con situaciones ficticias: consentimiento, presión, permanencia del contenido, no redistribución y rutas de ayuda.'},
 {title:'Grooming',summary:'Proceso en el que un adulto establece confianza con un menor para avanzar hacia solicitudes o conductas sexuales. Puede incluir regalos, secretos, aislamiento y amenazas.',action:'Enseñe señales concretas y enfatice que pedir ayuda no convierte al estudiante en responsable de lo ocurrido. Ante una revelación real, siga el protocolo institucional correspondiente.'},
 {title:'Ciberacoso',summary:'Agresión o daño mediante espacios digitales que puede repetirse y amplificarse por reenvíos, capturas y audiencias. Quien reenvía también puede aumentar el daño aunque no haya iniciado la agresión.',action:'Analice roles: persona afectada, quien agrede, quien observa y quien reenvía. Cierre con acciones posibles para cada rol.'},
 {title:'Deepfakes e inteligencia artificial',summary:'La IA generativa permite producir textos, imágenes, audio y video sintéticos. Esto modifica la forma de verificar información y abre riesgos como suplantación o imágenes íntimas falsas.',action:'Use ejemplos no sensibles para practicar verificación: fuente original, contexto, evidencia independiente y propósito del contenido.'},
 {title:'Huella digital, privacidad e identidad',summary:'La actividad en línea deja registros y puede circular fuera de la audiencia original. Privacidad no significa esconderse, sino tomar decisiones informadas sobre datos, contexto y personas con acceso.',action:'Trabaje casos donde el alumnado decida qué compartir, con quién y qué podría cambiar si el contenido sale de su contexto.'}
]};

export function guidanceFor(theme:AudienceSlug,level:string):GuidanceBlock|null{if(theme==='kids')return level==='preescolar'?KIDS_PRE:level==='primaria-alta'?KIDS_HIGH:KIDS_LOW;if(theme==='teens')return TEENS;if(theme==='families')return FAMILIES;if(theme==='teachers')return TEACHERS;return null;}
