import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DomSanitizer } from '@angular/platform-browser';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { map } from 'rxjs/operators';
import { ContentService } from '../core/services/content.service';
import { VideoItem } from '../core/models/content.models';

type CasiProfile='pb'|'pa'|'families'|'teachers';
type Guide={label:string;intro:string;before:string;after:string;action:string};
type EpisodeGuide={focus:string;profiles:Record<CasiProfile,Guide>};

const BASE:Record<CasiProfile,Guide>={
 pb:{label:'Primaria baja',intro:'Mira la historia para descubrir una señal de alerta y practicar qué hacer con ayuda de una persona adulta cuando la necesites.',before:'¿Qué crees que está a punto de pasar?',after:'¿Qué señal te avisó que algo no estaba bien?',action:'Elige una regla sencilla para recordarla después.'},
 pa:{label:'Primaria alta',intro:'Mira la historia, identifica el momento en que todavía se puede cambiar la decisión y piensa qué harías tú.',before:'¿En qué momento conviene detenerse y pensar?',after:'¿Qué decisión habría evitado el problema?',action:'Convierte lo aprendido en una decisión para tu vida digital.'},
 families:{label:'Familias',intro:'Miren la historia como punto de partida para conversar: primero escuchen qué piensa su hija o hijo y después construyan un acuerdo.',before:'Antes de verla, pregunten qué creen que puede ocurrir.',after:'Pregunten qué señal detectaron y qué apoyo esperarían de una persona adulta.',action:'Cierren con un acuerdo breve, claro y acorde con su edad.'},
 teachers:{label:'Docentes',intro:'Utiliza el episodio como detonador: presenta el dilema, escucha decisiones y cierra con una acción aplicable al grupo.',before:'Detén el título y pregunta qué decisión imaginan que aparecerá.',after:'Identifiquen señales, consecuencias, alternativas y formas de pedir ayuda.',action:'Construyan una regla o producto breve que pueda usarse fuera del aula.'}
};

const EPISODES:Record<string,EpisodeGuide>={
 'casi-yt-pEmFgQjDZ1g':{focus:'Convivencia, empatía y participación frente al cyberbullying',profiles:{
  pb:{label:'Primaria baja',intro:'Una historia para reconocer que una broma en internet puede lastimar cuando se comparte, se repite o deja sola a otra persona.',before:'Si te llega una burla o un meme sobre alguien de tu grupo, ¿qué podrías hacer antes de compartirlo?',after:'¿Cómo crees que se sintió la persona de la historia? ¿Quién pudo ayudar a detener la burla?',action:'Practica esta regla: si lastima a alguien, no lo comparto y pido ayuda.'},
  pa:{label:'Primaria alta',intro:'Una historia para analizar cuándo una broma se convierte en agresión y qué papel tienen quienes comparten, comentan o se quedan mirando.',before:'¿Compartir una burla “solo por risa” te hace parte del problema? Piensa por qué.',after:'¿Qué opciones tenía quien recibió o vio la agresión: no compartir, apoyar, reportar, guardar evidencia o pedir ayuda?',action:'Elige una forma concreta de no alimentar una agresión digital y de apoyar a quien la recibe.'},
  families:{label:'Familias',intro:'Este episodio permite conversar sobre humor, empatía y daño digital sin empezar desde el regaño o la revisión del teléfono.',before:'Pregunten: ¿cuándo una broma deja de ser divertida y empieza a hacer daño?',after:'Escuchen qué harían si fueran quien recibe la burla, quien la ve o quien ya la compartió.',action:'Acuerden qué hacer en casa si aparece una agresión: escuchar, guardar evidencia, bloquear o reportar y pedir apoyo.'},
  teachers:{label:'Docentes',intro:'Un detonador para trabajar cyberbullying desde los roles del conflicto: quien agrede, quien recibe, quien observa y quien puede intervenir.',before:'Antes del video, plantee: “Recibes un meme ofensivo sobre alguien del grupo. ¿Qué opciones tienes?”',after:'Analicen qué acciones aumentan el daño y cuáles lo frenan. Incluyan el papel de quienes observan.',action:'Construyan un protocolo breve de grupo: no reenviar, apoyar, conservar evidencia y acudir a una persona adulta responsable.'}
 }},
 'casi-yt-EmXJWNeYQZs':{focus:'Datos personales, desconocidos y búsqueda de ayuda',profiles:{
  pb:{label:'Primaria baja',intro:'Una historia para aprender que nombre completo, escuela, dirección, fotos o ubicación son datos que se cuidan.',before:'Si alguien que no conoces te pide tu escuela, tu dirección o una foto, ¿qué harías?',after:'¿Qué dato de la historia no debía compartirse? ¿A qué persona adulta de confianza se lo contarías?',action:'Recuerda tres pasos: no respondo, cierro o bloqueo y se lo cuento a una persona adulta.'},
  pa:{label:'Primaria alta',intro:'Una historia para distinguir entre conversar en línea y entregar información que puede identificarte o localizarte.',before:'Una persona parece amable en un juego o chat y pregunta dónde estudias. ¿Qué señales revisarías antes de responder?',after:'¿Qué información puede parecer pequeña pero, al juntarse, revelar demasiado sobre ti?',action:'Revisa una cuenta o juego: identifica qué datos muestras y cambia uno que no necesite ser público.'},
  families:{label:'Familias',intro:'Este episodio sirve para acordar qué información puede compartirse, cuál no y cómo pedir ayuda sin miedo cuando un desconocido hace preguntas.',before:'Antes del video, pregunten qué consideran “dato personal” y cuáles creen que nunca deberían dar a un desconocido.',after:'Comparen respuestas y hablen de qué harían si ya compartieron un dato: evitar el castigo facilita que pidan ayuda.',action:'Definan juntos tres datos que no se comparten y una persona adulta a quien acudir si algo incomoda.'},
  teachers:{label:'Docentes',intro:'Una situación para trabajar privacidad y protección de datos desde decisiones cotidianas, no desde definiciones abstractas.',before:'Pida clasificar ejemplos: nombre, apodo, escuela, ubicación, foto, contraseña. ¿Cuáles requieren mayor cuidado?',after:'Analicen cómo varios datos aparentemente aislados pueden permitir identificar o localizar a una persona.',action:'El grupo crea una guía de tres pasos ante solicitudes de datos de desconocidos: detenerse, no compartir y pedir apoyo.'}
 }},
 'casi-yt-lFs1izW9kpo':{focus:'Verificación de información y pensamiento crítico',profiles:{
  pb:{label:'Primaria baja',intro:'Una historia para descubrir que no todo lo que aparece en una pantalla es verdadero, aunque parezca emocionante o importante.',before:'Si una historia te sorprende mucho y quieres compartirla, ¿cómo podrías saber si es verdad?',after:'¿Qué pista te hizo dudar? ¿A quién podrías preguntar antes de compartir algo que no entiendes?',action:'Practica una pausa: antes de compartir, pregunto “¿cómo sé que esto es verdad?”'},
  pa:{label:'Primaria alta',intro:'Una historia para practicar la pausa antes de compartir y buscar señales que ayuden a distinguir información confiable de una historia inventada.',before:'¿Qué revisarías primero: quién lo publicó, la fecha, la fuente o si otros medios confiables dicen lo mismo?',after:'¿Qué hizo que la historia pareciera creíble y qué comprobación faltaba?',action:'Elige una publicación que hayas visto y comprueba al menos dos datos antes de creerla o compartirla.'},
  families:{label:'Familias',intro:'Este episodio permite modelar pensamiento crítico en casa: no se trata de desconfiar de todo, sino de mostrar cómo verificamos antes de compartir.',before:'Pregunten qué hace que una publicación parezca verdadera aunque no lo sea.',after:'Hagan juntos una comprobación sencilla: autor, fecha, fuente y confirmación en otro sitio confiable.',action:'Adopten una regla familiar: si provoca mucha urgencia, miedo o sorpresa, primero verificamos y después compartimos.'},
  teachers:{label:'Docentes',intro:'Un detonador para trabajar verificación de información con preguntas simples que el alumnado pueda reutilizar fuera del aula.',before:'Presente una afirmación llamativa y pregunte qué evidencia necesitarían antes de compartirla.',after:'Identifiquen fuente, autoría, fecha, evidencia y posibilidad de corroboración.',action:'Construyan una lista breve de verificación que pueda aplicarse a una publicación real.'}
 }},
 'casi-yt-0VnGrnTfgDU':{focus:'Descargas, enlaces y seguridad del dispositivo',profiles:{
  pb:{label:'Primaria baja',intro:'Una historia para aprender que un archivo, juego o premio “gratis” puede traer riesgos y que no es necesario resolverlo solo.',before:'Si una página te pide descargar algo para ganar un premio, ¿qué harías antes de tocar el botón?',after:'¿Qué señal avisaba que la descarga podía ser peligrosa? ¿Cuándo conviene llamar a una persona adulta?',action:'Recuerda: no descargo algo que no conozco sin pedir ayuda.'},
  pa:{label:'Primaria alta',intro:'Una historia para reconocer señales de riesgo antes de instalar archivos, aplicaciones o extensiones desde enlaces desconocidos.',before:'¿Qué revisarías antes de descargar: sitio oficial, permisos, remitente y si la oferta parece demasiado buena?',after:'¿En qué momento todavía se podía detener la descarga y verificar la fuente?',action:'Revisa una aplicación instalada: observa de dónde vino y qué permisos tiene.'},
  families:{label:'Familias',intro:'Este episodio ayuda a construir acuerdos sobre descargas e instalaciones sin convertir cada error en castigo.',before:'Pregunten qué tipos de descargas hacen y qué señales les harían desconfiar.',after:'Conversen sobre qué hacer si ya se abrió un archivo sospechoso: avisar pronto debe ser más importante que ocultar el error.',action:'Acuerden desde qué tiendas o sitios se instala y cuándo se pide autorización o ayuda.'},
  teachers:{label:'Docentes',intro:'Una situación para trabajar seguridad básica del dispositivo a partir de señales visibles: urgencia, premios, remitentes y fuentes no oficiales.',before:'Muestre ejemplos de mensajes de descarga y pida identificar qué les genera confianza o sospecha.',after:'Clasifiquen señales de riesgo y decisiones seguras antes, durante y después de una descarga.',action:'Elaboren una secuencia de tres pasos: detenerse, verificar la fuente y pedir apoyo si hay duda.'}
 }},
 'casi-yt-CtTLuyLp7vg':{focus:'Compras digitales, videojuegos y ofertas engañosas',profiles:{
  pb:{label:'Primaria baja',intro:'Una historia para comprender que monedas, skins y objetos virtuales pueden costar dinero real y que las compras se hacen con una persona adulta.',before:'Si un juego ofrece algo que quieres comprar, ¿qué haces antes de pagar o tocar un enlace?',after:'¿Qué parte de la oferta parecía atractiva y qué riesgo podía esconder?',action:'Recuerda: no uso tarjetas, contraseñas ni dinero real sin permiso y acompañamiento adulto.'},
  pa:{label:'Primaria alta',intro:'Una historia para analizar ofertas dentro y fuera de videojuegos, reconocer precios sospechosos y proteger cuentas y formas de pago.',before:'Una página ofrece monedas o un juego mucho más barato que la tienda oficial. ¿Qué comprobarías?',after:'¿Qué señales podían indicar una estafa: precio increíble, enlace externo, urgencia o petición de datos?',action:'Antes de una compra digital, compara el sitio con el canal oficial y no compartas contraseña ni datos de pago.'},
  families:{label:'Familias',intro:'Este episodio abre una conversación sobre dinero real dentro de entornos de juego, compras impulsivas y acuerdos familiares claros.',before:'Pregunten qué entienden por monedas virtuales, skins y compras dentro de una aplicación.',after:'Hablen de cómo reconocer una oferta falsa y qué hacer si aparece una compra que no reconocen.',action:'Definan un acuerdo: cuándo se puede comprar, quién autoriza y qué medios de pago nunca se comparten.'},
  teachers:{label:'Docentes',intro:'Una situación para trabajar ciudadanía económica digital: valor del dinero, compras dentro de juegos y señales de fraude.',before:'Plantee una oferta ficticia de monedas o un videojuego con descuento extremo. ¿Qué deberían verificar?',after:'Analicen persuasión, urgencia, canales oficiales, datos de pago y consecuencias de compartir credenciales.',action:'El grupo redacta una lista de verificación para compras digitales seguras.'}
 }}
};

@Component({selector:'app-casi-learning',standalone:true,imports:[CommonModule,RouterLink],templateUrl:'./casi-learning.html',styleUrl:'./casi-learning.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class CasiLearningComponent{
 private content=inject(ContentService);private sanitizer=inject(DomSanitizer);private route=inject(ActivatedRoute);private q=toSignal(this.route.queryParamMap.pipe(map(p=>p.get('perfil'))),{initialValue:null});
 profile=signal<CasiProfile>('pb');serie=computed(()=>this.content.getSeriesBySlug('el-dia-que-casi'));videos=computed(()=>this.serie()?.videos??[]);selected=signal<VideoItem|null>(null);
 episodeGuide=computed(()=>this.selected()?EPISODES[this.selected()!.id]:undefined);guide=computed(()=>this.episodeGuide()?.profiles[this.profile()]??BASE[this.profile()]);focus=computed(()=>this.episodeGuide()?.focus??'Reconocer riesgos y tomar decisiones a tiempo');
 playlistUrl=computed(()=>this.sanitizer.bypassSecurityTrustResourceUrl('https://www.youtube-nocookie.com/embed/videoseries?list='+(this.serie()?.youtubePlaylistId??'PL6UhGvZdF4uhkptPgZt5UpoFiK1WQyig4')));videoUrl=computed(()=>{const v=this.selected();if(!v)return this.playlistUrl();return this.sanitizer.bypassSecurityTrustResourceUrl('https://www.youtube-nocookie.com/embed/'+this.videoId(v.youtubeUrl)+'?rel=0')});
 constructor(){const raw=this.q();if(raw==='pa'||raw==='families'||raw==='teachers')this.profile.set(raw)} setProfile(p:CasiProfile){this.profile.set(p)} play(v:VideoItem){this.selected.set(v);window.scrollTo({top:0,behavior:'smooth'})}showPlaylist(){this.selected.set(null)}private videoId(url:string){try{return new URL(url).searchParams.get('v')??''}catch{return ''}}
}
