import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';import { RouterLink } from '@angular/router';import { AUDIENCE_PAGES } from '../core/data/page-content';
type Aud='all'|'kids'|'teens'|'families'|'teachers';type Topic='all'|'security'|'relations'|'wellbeing'|'critical'|'ai'|'create'|'participation'|'consumer';
interface Entry{title:string;description:string;aud:Exclude<Aud,'all'>;stage:string;topic:Exclude<Topic,'all'>;format:string;href:string;collection?:string}
const audMap:Record<string,Exclude<Aud,'all'>>={'ninas-y-ninos':'kids','adolescentes':'teens','familias':'families','docentes':'teachers'};
function topicFor(s:string):Exclude<Topic,'all'>{const x=s.toLowerCase();if(/ia|inteligencia|deepfake|algorit/.test(x))return'ai';if(/acoso|presi|respeto|chat|cariño|consent|emoci/.test(x))return'relations';if(/fomo|pantalla|bienestar|descanso|atenci/.test(x))return'wellbeing';if(/fraud|contraseña|privacidad|dato|segur|virus|perfil|mundo privado/.test(x))return'security';if(/compra|moneda|mercado|dinero/.test(x))return'consumer';if(/fuente|inform|viral|noticia/.test(x))return'critical';return'create'}
const entries:Entry[]=AUDIENCE_PAGES.flatMap(p=>p.subLevels.flatMap(l=>(l.levelResources??[]).map(r=>({title:r.title,description:r.description,aud:audMap[p.slug]??'teachers',stage:l.title,topic:topicFor(r.title+' '+r.description),format:r.typeLabel||r.type,href:'/p/'+p.slug+'#'+l.id})))) as Entry[];
entries.push({title:'El día que casi…',description:'Historias breves para analizar decisiones, señales de riesgo y formas de actuar.',aud:'kids',stage:'Primaria',topic:'relations',format:'Historia + video',href:'/el-dia-que-casi',collection:'El día que casi…'},{title:'EduTips',description:'Actividades educativas que parten de situaciones y utilizan el video como refuerzo.',aud:'teens',stage:'Adolescentes',topic:'critical',format:'Actividad + video',href:'/edutips',collection:'EduTips'});
@Component({selector:'app-recursos',standalone:true,imports:[CommonModule,RouterLink],templateUrl:'./recursos.html',styleUrl:'./recursos.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class RecursosComponent{aud=signal<Aud>('all');topic=signal<Topic>('all');audiences=[['all','Todos'],['kids','Niñas y niños'],['teens','Adolescentes'],['families','Familias'],['teachers','Escuela']] as const;topics=[['all','Todos los temas'],['security','Seguridad y privacidad'],['relations','Convivencia y relaciones'],['wellbeing','Bienestar digital'],['critical','Información y pensamiento crítico'],['ai','Inteligencia artificial'],['create','Crear y aprender'],['participation','Participación y ciudadanía'],['consumer','Consumo y decisiones']] as const;results=computed(()=>entries.filter(e=>(this.aud()==='all'||e.aud===this.aud())&&(this.topic()==='all'||e.topic===this.topic())));audLabel(a:Entry['aud']){return this.audiences.find(x=>x[0]===a)?.[1]??a}}
